sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_88666fb0735c_key -iv $encrypted_88666fb0735c_iv -in multi-k8s-288919-206d747d7627.json.enc -out multi-k8s-288919-206d747d7627.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - sourc $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
