apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  #  this ClusterIP service gives access to the set of pods "web" inside the node and exposes them
  #  to other services in the cluster
  selector:
    component: web
  ports:
    - port: 3000
      targetPort: 3000
